name: Activity Player  CI/CD

on:
  push:
    branches:
      - main
      - develop
      - release/*

  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  test:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Install Dependencies
      run: npm install -f
    - name: Build
      run: npm run build
